### ISSUE TITLE
Fix upstream vulnerability in lodash 4.7.11

### ISSUE THREAD

**Issue by pastelmind** [yargs/yargs-unparser#35]
There is a [new vulnerability](https://github.com/lodash/lodash/pull/4336) in lodash 4.17.11. ([This issue](https://github.com/lodash/lodash/issues/4348) may be related) Could you please update your dependency to lodash >= 4.17.13 to fix it?

**Comment by Whathecode** [comment]
FYI, there is a typo in the title: the vulnerability is in `lodash` 4.17.11, not 4.7.11. :)

**Comment by bcoe** [comment]
this has been addressed in `yargs-unparser@next`, which will be promoted soon.
